### ISSUE TITLE
What permissions does a role need for alert manager?

### ISSUE THREAD

**Issue by nickbijmoer** [simcen/alert_manager#168] opened 2016-12-14 09:18 UTC
See title :)

**Comment by simcen** [comment] 2016-12-16 10:13
Thanks for the question.
To create incidents, the owner of the alert needs these capabilities:
- edit_tcp
- list_settings
- schedule_search

To be an owner of an incident, it requires the
- am_is_owner
capability. 

To fully use the Alert Manager dashboards and edit incidents, the built-in Splunk "user" role is enough. Of course, the role needs read permissions to the app.

My recommendation:
- Assign the "alert_manager_user" role to all users which need to use the App (grants read access and necessary capabilities to be an owner of an incident)
- Use the "alert_manager" role for the owner of the alerts (grants necessary capabilities to  create an incident from an alert)

Will add this to the documentation too.

**Comment by nickbijmoer** [comment] 2016-12-16 10:50
Okey so I got a "viewer"role in splunk which can only view things. But as soon as he wants to go to the alert manager page he will get Page not found error. But when I go to that page with admin account it just works. Do you know a solution for this ? :)

**Comment by talowery** [comment] 2017-02-20 21:28
I'm encountering the same issue.  A user assigned the "alert_manager_user" is not able to access the app regardless of the permission assigned the "alert_manager_user" role.  However if I assign that same user "alert_manager"  role and allow the role to inherit everything from role alert_manager_user, it works.
Version is 2.14, Splunk 6.5.0

**Comment by johnfromthefuture** [comment] 2017-03-01 19:51
Downloaded a fresh copy of alert manager from splunkbase, installed on my test box (6.5.1) and confirmed the issue is permission related.

![image](https://cloud.githubusercontent.com/assets/19210786/23478138/595abde6-fe8e-11e6-9aec-67bf1113003c.png)

In the development branch, the default.meta file has been updated appropriately to accommodate the updated user roles provided by the app. In the version on Splunkbase, this doesn't appear to be the case. You should be able to correct the issue by having an admin update permissions on the app to grant read access to the alert_manager_user role.

I'm sure the updated default.meta file will be included in the next update release.

**Comment by johnfromthefuture** [comment] 2017-03-02 02:22
Expect the issue to be resolved per last commit.

**Closed by johnfromthefuture** 2017-03-02 02:22 UTC
